### ISSUE TITLE
Run JDT OSGI examples

### ISSUE THREAD

**Issue by hongxuchen** [jmini/jdt-experiments#5]
I'm trying to use JDT outside eclipse to analyze java Maven/Gradle projects and came across [your article](https://jmini.github.io/blog/2020/2020-01-17_jdt-without-eclipse.html) and this repository. For now, I have some trials on [programcreek-osgi](https://github.com/jmini/jdt-experiments/tree/master/programcreek-examples/programcreek-osgi):

```
mvn verify
java -jar ~/biz.aQute.bnd-3.5.0.jar package application.bndrun
```
Afterwards, I got a `application.jar` which contains the following files:

![image](https://user-images.githubusercontent.com/843267/167333612-ccaaf3a4-f265-4348-a3d4-a0344868acfb.png)

where inside `programcreek-osgi-1.0.0.202205070907.jar` there are
![image](https://user-images.githubusercontent.com/843267/167333764-e3c6b9fe-fb0a-4b37-b42c-46a2ecd391d2.png)

But I don't know how to proceed to make `InsertCommentsTest`/`InsertStatementsTest` work. 
1. `java -jar application.jar` does not work.
2. I'm confused with what [README](https://github.com/jmini/jdt-experiments/blob/master/programcreek-examples/programcreek-osgi/README.adoc) tells.

Am I missing something?

**Comment by jmini** [comment]
I wrote those 2 projects [`programcreek-osgi`](https://github.com/jmini/jdt-experiments/tree/master/programcreek-examples/programcreek-osgi) and [`programcreek-standalone`](https://github.com/jmini/jdt-experiments/tree/master/programcreek-examples/programcreek-standalone) to illustrate how to use [Eclipse JDT without eclipse](https://jmini.github.io/blog/2020/2020-01-17_jdt-without-eclipse.html).

---
What I can tell about your question:

The tests are executed by Maven, when you run:

```
mvn verify
```

The 2 tests `InsertCommentsTest` and `InsertStatementsTest` are executed by the `bnd-testing-maven-plugin`, as you can see here:

```
[INFO] --- bnd-testing-maven-plugin:5.2.0:testing (default) @ programcreek-osgi ---
[INFO] Matching glob *
[INFO] -runbundles: com.ibm.icu;version='[65.1.0,65.1.1)',org.apache.servicemix.bundles.junit;version='[4.12.0,4.12.1)',org.eclipse.core.commands;version='[3.9.600,3.9.601)',org.eclipse.core.contenttype;version='[3.7.500,3.7.501)',org.eclipse.core.expressions;version='[3.6.600,3.6.601)',org.eclipse.core.filesystem;version='[1.7.600,1.7.601)',org.eclipse.core.jobs;version='[3.10.600,3.10.601)',org.eclipse.core.resources;version='[3.13.600,3.13.601)',org.eclipse.core.runtime;version='[3.17.0,3.17.1)',org.eclipse.equinox.app;version='[1.4.300,1.4.301)',org.eclipse.equinox.common;version='[3.10.600,3.10.601)',org.eclipse.equinox.preferences;version='[3.7.600,3.7.601)',org.eclipse.equinox.registry;version='[3.8.600,3.8.601)',org.eclipse.jdt.core;version='[3.20.0,3.20.1)',org.eclipse.text;version='[3.10.0,3.10.1)',programcreek-osgi;version='[1.0.0,1.0.1)'
[INFO] No Errors
```

I modified the expected value:
https://github.com/jmini/jdt-experiments/blob/ff0e464daed3a126df1c983c080c91f1e657ded5/programcreek-examples/programcreek-osgi/src/main/java/example/InsertCommentsTest.java#L117-L129

And I saw the tests failing.

```
TEST test(example.InsertCommentsTest) <<< ERROR: ...
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at example.InsertCommentsTest.test(InsertCommentsTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at aQute.junit.Activator.test(Activator.java:355)
	at aQute.junit.Activator.automatic(Activator.java:267)
	at aQute.junit.Activator.run(Activator.java:188)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at aQute.launcher.Launcher.launch(Launcher.java:452)
	at aQute.launcher.Launcher.run(Launcher.java:181)
	at aQute.launcher.Launcher.main(Launcher.java:157)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

---

I don't know exactly how bnd is running the tests in details. I guess you could ask the bnd project directly (I think they are also quite active on stackoverflow).

If you run with `-X` you have more details about what is executed:

```
mvn -X verify
```

I hope this helps…

**Comment by hongxuchen** [comment]
Thanks so much for the detailed explanation! !

Now I understand that the [programcreek-osgi](https://github.com/jmini/jdt-experiments/tree/master/programcreek-examples/programcreek-osgi) example is mainly for the proof that equinox osgi can work  outside eclipse with bnd-maven-plugin. I followed your tips and it indeed worked as you said.

I will dig a bit more and will ask the bnd team directly if I still fail to make it.
